# -*- coding: utf-8 -*-
"""Generates the Korean Samjho brand mark.

Design rationale
----------------
The previous mark was the letter ㅎ. That only reads as "Korean" to somebody who
already knows Hangul — which is precisely who this app is NOT for. The mark has to
say "learn to speak Korean" to a beginner who has never seen the script.

So: 한 (the character for "Korea") over three dots. 한 is visually identifiable as
Korean script even to a non-reader, and three dots are a universal chat/speech
signal. Together they read as "speak Korean" without requiring literacy in Hangul.

The glyph outline is taken from the bundled Noto Sans KR Bold (SIL OFL 1.1) so the
letterform is typographically correct rather than hand-approximated.

Outputs: adaptive-icon background/foreground/monochrome, splash mark, Play Store PNG.
"""
import os, math
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.misc.transform import Transform
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
APP  = os.path.join(HERE, "..", "..", "app")
RES  = os.path.join(APP, "src", "main", "res")
TTF  = os.path.join(RES, "font", "noto_sans_kr_bold.ttf")
BRAND = os.path.join(HERE, "..", "..", "brand")
os.makedirs(BRAND, exist_ok=True)

# --- palette -------------------------------------------------------------
# Deep indigo -> violet. Deliberately not green (Duolingo), orange (Memrise,
# Babbel) or plain blue (Busuu, LingoDeer), so the icon is distinguishable in a
# store grid of language apps. Coral accent carries the brand's warm secondary.
GRAD_START = "#1E3A8A"
GRAD_END   = "#7C3AED"
MARK       = "#FFFFFF"
ACCENT     = "#FF7A5C"

VIEW = 108.0          # adaptive icon viewport
CX   = 54.0
GLYPH_H = 44.0        # cap height of 한 in viewport units
GLYPH_CY = 46.0
DOT_R = 4.6
DOT_Y = 79.0
DOT_GAP = 11.5

def glyph_path(char, target_h, cx, cy):
    font = TTFont(TTF)
    gs = font.getGlyphSet()
    name = font.getBestCmap()[ord(char)]
    bp = BoundsPen(gs)
    gs[name].draw(bp)
    x0, y0, x1, y1 = bp.bounds
    scale = target_h / (y1 - y0)
    t = (Transform()
         .translate(cx, cy)          # 3. move to final centre
         .scale(scale, -scale)       # 2. scale and flip Y (font is Y-up, canvas Y-down)
         .translate(-(x0 + x1) / 2.0, -(y0 + y1) / 2.0))  # 1. centre on origin
    pen = SVGPathPen(gs, ntos=lambda v: f"{v:.2f}")
    gs[name].draw(TransformPen(pen, t))
    d = pen.getCommands()
    # report the transformed bounds so the layout can be verified numerically
    bp2 = BoundsPen(gs)
    gs[name].draw(TransformPen(bp2, t))
    return d, bp2.bounds

def dots_path():
    """Three dots as bezier circles — one path so the monochrome layer stays single-colour."""
    parts = []
    for i in (-1, 0, 1):
        cx = CX + i * DOT_GAP
        r = DOT_R
        k = r * 0.5523
        parts.append(
            f"M{cx - r:.2f},{DOT_Y:.2f}"
            f"C{cx - r:.2f},{DOT_Y - k:.2f} {cx - k:.2f},{DOT_Y - r:.2f} {cx:.2f},{DOT_Y - r:.2f}"
            f"C{cx + k:.2f},{DOT_Y - r:.2f} {cx + r:.2f},{DOT_Y - k:.2f} {cx + r:.2f},{DOT_Y:.2f}"
            f"C{cx + r:.2f},{DOT_Y + k:.2f} {cx + k:.2f},{DOT_Y + r:.2f} {cx:.2f},{DOT_Y + r:.2f}"
            f"C{cx - k:.2f},{DOT_Y + r:.2f} {cx - r:.2f},{DOT_Y + k:.2f} {cx - r:.2f},{DOT_Y:.2f}Z"
        )
    return "".join(parts)

han, bounds = glyph_path("한", GLYPH_H, CX, GLYPH_CY)
dots = dots_path()
print(f"한 bounds in viewport: x {bounds[0]:.1f}..{bounds[2]:.1f}  y {bounds[1]:.1f}..{bounds[3]:.1f}")
top, bot = bounds[1], DOT_Y + DOT_R
print(f"mark spans y {top:.1f}..{bot:.1f}  (adaptive safe zone is 21..87)")
assert top >= 21 and bot <= 87, "mark falls outside the adaptive-icon safe zone"
assert bounds[0] >= 21 and bounds[2] <= 87, "mark too wide for the safe zone"

def write(path, body):
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)
    print("  wrote", os.path.relpath(path, os.path.join(HERE, "..", "..")))

# --- adaptive icon background: full-bleed gradient ------------------------
write(os.path.join(RES, "drawable", "ic_launcher_background.xml"), f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by content/tools/build_icon.py — do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient android:type="linear"
                android:startX="0" android:startY="0"
                android:endX="108" android:endY="108">
                <item android:offset="0" android:color="{GRAD_START}" />
                <item android:offset="1" android:color="{GRAD_END}" />
            </gradient>
        </aapt:attr>
    </path>
</vector>
""")

# --- adaptive icon foreground: 한 + speech dots ---------------------------
write(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"), f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by content/tools/build_icon.py — do not edit by hand.
     한 = "Korea"; the three dots read as speech/chat, so the mark says
     "speak Korean" even to someone who cannot read Hangul yet. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:fillColor="{MARK}" android:pathData="{han}" />
    <path android:fillColor="{ACCENT}" android:pathData="{dots}" />
</vector>
""")

# --- monochrome layer for Android 13 themed icons -------------------------
write(os.path.join(RES, "drawable", "ic_launcher_monochrome.xml"), f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by content/tools/build_icon.py — do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:fillColor="#FFFFFF" android:pathData="{han}" />
    <path android:fillColor="#FFFFFF" android:pathData="{dots}" />
</vector>
""")

# --- splash mark ---------------------------------------------------------
write(os.path.join(RES, "drawable", "ic_splash_logo.xml"), f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by content/tools/build_icon.py — do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:fillColor="{MARK}" android:pathData="{han}" />
    <path android:fillColor="{ACCENT}" android:pathData="{dots}" />
</vector>
""")

# --- adaptive icon wrapper ----------------------------------------------
adaptive = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""
for n in ("ic_launcher.xml", "ic_launcher_round.xml"):
    write(os.path.join(RES, "mipmap-anydpi-v26", n), adaptive)

# --- Play Store icon: 512x512 PNG, same face, same layout ----------------
def hexrgb(h): return tuple(int(h[i:i + 2], 16) for i in (1, 3, 5))

S = 512
img = Image.new("RGB", (S, S), hexrgb(GRAD_START))
d = ImageDraw.Draw(img)
c0, c1 = hexrgb(GRAD_START), hexrgb(GRAD_END)
# diagonal gradient, matching the vector's 0,0 -> 108,108 direction
for i in range(2 * S):
    t = i / (2 * S - 1)
    col = tuple(round(c0[j] + (c1[j] - c0[j]) * t) for j in range(3))
    d.line([(i, 0), (0, i)], fill=col)

scale = S / VIEW
fnt_px = 1
# find the pixel size whose rendered 한 matches GLYPH_H in viewport units
target_px = GLYPH_H * scale
lo, hi = 10, 900
while lo < hi:
    mid = (lo + hi) // 2
    f = ImageFont.truetype(TTF, mid)
    bb = f.getbbox("한")
    if (bb[3] - bb[1]) < target_px: lo = mid + 1
    else: hi = mid
fnt_px = lo
f = ImageFont.truetype(TTF, fnt_px)
bb = f.getbbox("한")
gw, gh = bb[2] - bb[0], bb[3] - bb[1]
gx = CX * scale - gw / 2 - bb[0]
gy = GLYPH_CY * scale - gh / 2 - bb[1]
d.text((gx, gy), "한", font=f, fill=hexrgb(MARK))
for i in (-1, 0, 1):
    cx = (CX + i * DOT_GAP) * scale
    cy = DOT_Y * scale
    r = DOT_R * scale
    d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=hexrgb(ACCENT))
out = os.path.join(BRAND, "playstore-icon-512.png")
img.save(out, "PNG")
print("  wrote", os.path.relpath(out, os.path.join(HERE, "..", "..")), f"({fnt_px}px face)")

# a small preview strip for the docs
prev = img.resize((192, 192), Image.LANCZOS)
prev.save(os.path.join(BRAND, "icon-preview-192.png"), "PNG")
print("  wrote brand/icon-preview-192.png")
